name: Build and Test PyFlow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.7"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pybind11 pytest

      - name: Set up MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: List wheel files
        run: |
          python -c "import os; print('\n'.join(os.listdir('dist')))"

      - name: Install package
        run: |
          python -m pip install $(python -c "import glob; files = glob.glob('dist/*.whl'); print(files[0])")

      - name: Run tests
        run: |
          cd tests/python
          pytest

